[package]
name = "rkaiq-sys"
version = "0.1.0"
edition = "2021"
description = "Rockchip RKAIQ FFI bindings for Rust"
authors = [ "Varphone Wong <varphone@qq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.59.2"
