[package]
name = "rkaiq"
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"
categories = ["embedded", "external-ffi-bindings", "graphics"]
description = "Rockchip RKAIQ bindings for Rust"
documentation = "https://docs.rs/rkaiq"
repository = "https://github.com/varphone/rkaiq.git"
authors = [ "Varphone Wong <varphone@qq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkaiq-sys = { version = "0.1.5", path = "rkaiq-sys" }
regex = "1"

[dev-dependencies]
gst = { version = "0.20", package = "gstreamer" }
gst-base = { version = "0.20", package = "gstreamer-base" }
gst-video = { version = "0.20", package = "gstreamer-video" }
log = { version = "0.4", features = ["std"] }
pretty_env_logger = "0.4"

[features]
default = ["rel_2_0"]
fullv = []
rel_1_0 = []
rel_2_0 = []

[workspace]
members = [
    "rkaiq-sys",
]
